### ISSUE TITLE
Setting File issue

### ISSUE THREAD

**Issue by INFJ-BA** [ShyKiss/outlast-all-all-persistent#1]
Hi,So I do everyting you ask,but in the step 5,I find myself not able to type anything. It says Couldn't find setting file,attempting to download setting files.Please help me.

**Comment by ShyKiss** [comment]
Try drop this in Outlast directory along with Level_Launcher.bat [Settings.zip](https://github.com/ShyKiss/outlast-all-all-persistent/files/8768182/Settings.zip)

**Comment by INFJ-BA** [comment]
> It works.but I can't type. It says
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
For a list of commands type [Help]
Please do not close the script while Outlast is running.
If a line that says [Terminate batch job] shows up type [N]

Changelog:

curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by INFJ-BA** [comment]
Thank you! It work!
